name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Deploy to /docs
      run: |
        rm -rf docs
        mv build docs
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git add docs
        git commit -m "Deploy to GitHub Pages"
        git push origin main
